name = "Langevin"
uuid = "42433972-eea5-42bb-ab72-392315b4e8df"
version = "0.2.9"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]

[deps]
KitBase = "86eed249-3a28-466f-8d3a-596821e1af9a"
PolyChaos = "8d666b04-775d-5f6e-b778-5ac7c70f65a3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
KitBase = "0.8, 0.9"
PolyChaos = "0.2, 1"
Reexport = "^1"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
